# Connessione PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/posgres
spring.datasource.username=postgres
spring.datasource.password=032014

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=a-very-long-and-secret-key-that-is-at-least-256-bits-long
jwt.expiration=3600000
